### PR TITLE
Temp in F for people who use temp in F.   

### PR DESCRIPTION
**Pull request by ELY3M**
I was bothered by the temp in C so I added the converting code to have temp in F.  
I keep both C and F temps.

### CODE REVIEW

**Comment by deadair3210** [comment]
Celsius is usually used in tech due to finer detail in the measurements, but as long as you keep both I guess it would be fine

**Comment by yellows8** [comment]
C / F for display, if anything?

**Comment by ELY3M** [comment]
C / F is good idea.   I'm sorry for my comments.  I just want to keep track of the mods I did.  you can clean it up if you decide to add the mod.

**Comment by yellows8** [comment]
Those comments should be removed by you...

**Comment by ELY3M** [comment]
I just removed comments.

**Comment by fincs** [comment]
ºC should be given preference. ºF is only used by a very small number of countries. I'd say there should be a setting to display which units to use; if this PR is to be accepted.

**Comment by ELY3M** [comment]
I also replaced tables with spaces.

**Comment by ELY3M** [comment]
ok I will look into using config settings.  it is good idea :)

**Comment by fincs** [comment]
Closing, due to PR repo descending into a rebrand fork. If anyone wants to have a go at implementing this properly, feel free to submit a new PR.

**Comment by ELY3M** [comment]
I know it has been years.    
I just re-did my repo and I wanted to do this again proper and clean way and ability to set via config.

**Pull request closed without merging**
