### PR TITLE
Improved Japanese language support for "common/language.c".

### PR DESCRIPTION
**Pull request by yyprogram**
* Improved slight ~ serious Japanese translation miss.
* Added new STR_JP() for "Back", "OK", "LastLoadResult".

I'm sorry if I missed something.

### CODE REVIEW

**Comment by yellows8** [comment]
This should be in #19.

**Comment by yyprogram** [comment]
I apologise.
I'll delete this request.

**Comment by yellows8** [comment]
You can do that via PRing this to here: https://github.com/AntonioDePau/nx-hbmenu/tree/patch-2

**Comment by yellows8** [comment]
merged 13676f64fd51da1e6e5e8fa0b5dade15d57c1c21

**Pull request closed without merging**
