### PR TITLE
Added french strings

### PR DESCRIPTION
**Pull request by MehdiKhelfi**

### CODE REVIEW

**Comment by MehdiKhelfi** [comment]
Well , in fact "ok" in french is also "ok"  , so I don't think I need to add it

**Comment by MehdiKhelfi** [comment]
https://github.com/MehdiKhelfi/nx-hbmenu/commit/fff0b02aab07335da6f1670c42be20f7cc11746b

**Comment by yellows8** [comment]
Can you add it anyway & add the aforementioned period?

**Comment by yellows8** [comment]
https://github.com/MehdiKhelfi/nx-hbmenu/commit/fff0b02aab07335da6f1670c42be20f7cc11746b <- This commit is on the patch-3 branch, while this PR is on the patch-2 branch.

**Comment by MehdiKhelfi** [comment]
https://github.com/MehdiKhelfi/nx-hbmenu/commit/efbc92db403827e4ada3c3f5a4c7084a47913068

**Comment by MehdiKhelfi** [comment]
https://github.com/MehdiKhelfi/nx-hbmenu/commit/01430abddb611b224b7a2d114ea520b90d2a6084

**Comment by MehdiKhelfi** [comment]
> Can you add it anyway & add the aforementioned period?

What do you mean by period ?

**Comment by MehdiKhelfi** [comment]
https://github.com/MehdiKhelfi/nx-hbmenu/commit/faa27ef189ecc1b3ae18321c0a9176c246d56c1a

**Pull request merged**
